'use strict';
const $=id=>document.getElementById(id);
const colors=['#67e2b4','#ffa878','#71baf7','#d0a1ff','#ffe177','#f27ea2','#91d2ce','#b4cc83'];
const terrain=['平地','道路','山地','池'], terrainColors=['#c5c5a2','#637780','#9d7d5b','#244e67'];
const directions=[[0,1,-1],[1,0,-1],[1,-1,0],[0,-1,1],[-1,0,1],[-1,1,0]];
const state={data:null,map:'',day:0,t:0,selected:null,playing:false,zoom:1,pan:{x:0,y:0},follow:false,timelines:[],last:0,request:0};
const canvas=$('field'),ctx=canvas.getContext('2d');let view={},drag=null;
async function api(path,options){const r=await fetch(path,options);const d=await r.json();if(!r.ok)throw Error(d.error||'通信に失敗しました');return d;}
function badge(el,text,type=''){el.textContent=text;el.className='badge '+type;}
function cube(pos,w){const row=Math.floor(pos/w),col=pos%w,x=col-Math.ceil(row/2);return[x,-x-row,row];}
function cellId(c,w){return c[2]*w+c[0]+Math.ceil(c[2]/2);}
function screenPos(pos){const w=state.data.source.map.width,row=Math.floor(pos/w),col=pos%w;return{x:Math.sqrt(3)*12*(col-(row%2)/2),y:18*row};}
function point(pos){const p=screenPos(pos);return{x:view.x+p.x*view.scale,y:view.y+p.y*view.scale};}
function days(){return state.data?.result.events.filter(e=>e.type==='day')||[];}
function snapshot(){return days().find(d=>d.day===state.day);}
function plan(){let day=-1,found=null;for(const e of state.data?.result.events||[]){if(e.type==='day')day=e.day;if(e.type==='post'&&(e.endpoint==='/'||e.endpoint==='')&&(e.day??day)===state.day)found=e;}return found;}
function revision(){try{return JSON.parse(plan()?.body||'{}').revision;}catch{return undefined;}}
function acceptedCount(){return(state.data?.result.events||[]).filter(e=>e.type==='post'&&(e.endpoint==='/'||e.endpoint==='')&&(()=>{try{return JSON.parse(e.body).revision>0;}catch{return false;}})()).length;}
function duration(pos,snap){const s=state.data.source,code=s.map.cells[Math.floor(pos/s.map.width)]?.[pos%s.map.width];if(code===1){const status=(snap?.traffics||[]).find(x=>x.pos===pos)?.status||0;return[1,2,4][status];}return[2,0,3,Infinity][code];}
function build(){const snap=snapshot(),payload=plan()?.payload;state.timelines=[];if(!snap)return;for(let id=0;id<snap.agents.length;id++){let pos=snap.agents[id].pos,t=0;const segments=[],route=[pos],actions=payload?.[id]||[];for(const action of actions){if(!Number.isInteger(action)){segments.push({from:pos,to:pos,start:t,end:t,invalid:true});break;}if(action<0){segments.push({from:pos,to:pos,start:t,end:t-action,wait:true});t-=action;continue;}if(action>5)break;const c=cube(pos,state.data.source.map.width),next=cellId(c.map((v,j)=>v+directions[action][j]),state.data.source.map.width),cost=duration(pos,snap);if(!Number.isFinite(cost))break;segments.push({from:pos,to:next,start:t,end:t+cost});t+=cost;pos=next;route.push(pos);}state.timelines.push({id,route,segments,steps:t});}}
function carAt(id){const snap=snapshot();if(!snap)return null;let pos=snap.agents[id].pos,wait=false;for(const seg of state.timelines[id]?.segments||[]){if(state.t<seg.start)break;if(state.t<seg.end){pos=seg.from;wait=!!seg.wait;break;}pos=seg.to;}return{pos,wait};}
function formatMissing(brands){return brands==null?'未集計':brands.length?brands.join(', '):'なし';}
function renderResults(){const stats=state.data?.stats,known=stats&&(stats.method!=='replay'||stats.known_days.length>0);$('result-types').textContent=known?stats.total_types+' 種類':(stats?'未集計':'未取得');$('result-count').textContent=known?stats.total_count+' 個':(stats?'未集計':'未取得');$('result-daily-types').textContent=known?stats.cumulative_types+' 種類':(stats?'未集計':'未取得');$('result-missing').textContent=(stats?.complete&&stats.missing_brands?.length===0?'なし（全種類制覇）':formatMissing(stats?.missing_brands));$('daily-results').replaceChildren();for(let day=0;day<(state.data?.source.daySteps.length||0);day++){const r=stats?.days[day],el=document.createElement('div');el.className='daily-result';el.innerHTML='<small>'+(day+1)+'日目の獲得種類数</small><strong>'+(r&&r.types!==null?r.types+' 種類':'未集計')+'</strong><small>未取得ブランド：'+formatMissing(r?.missing_brands)+'</small>';$('daily-results').append(el);}$('result-note').textContent=stats?(stats.method==='imported'?'読み込んだ獲得履歴の集計です。':'募集要項のルールによる採用回答の再生集計です。公式スコアAPIの値ではありません。日開始時にスポットにいる巡回車も、在庫の範囲内で獲得に数えます。'+(!stats.complete?' 未集計の日を除く途中集計です。':'')+(stats.notes?.length?' '+stats.notes.join(' / '):'')):'日次データを受信すると、採用された回答から獲得結果を集計します。未取得は獲得数0を意味しません。';}
$('result-file').onchange=async()=>{const file=$('result-file').files[0];if(!file)return;try{const records=JSON.parse(await file.text());await api('/api/result',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({map:state.map,records})});await load();}catch(e){$('notice').textContent='獲得履歴: '+e.message;}finally{$('result-file').value='';}};
function renderUI(){if(!state.data)return;renderResults();const s=state.data.source,r=state.data.result,snap=snapshot(),p=plan(),rev=revision();$('map-size').textContent=s.map.width+' × '+s.map.height;$('day-count').textContent=days().length+' / '+s.daySteps.length;$('accepted').textContent=acceptedCount()+' / '+s.daySteps.length;$('match-state').textContent=r.error?'エラー':r.running?'実行中':r.completed?'完了':'未実行';badge($('connection'),r.running?'LIVE · 観測中':'REPLAY · 試合記録',r.running?'good':'');$('field-title').textContent=state.map+' · '+(state.day+1)+'日目';$('notice').textContent=r.error?r.error.split('\n').filter(Boolean).slice(-1)[0]:'';$('step').max=s.daySteps[state.day];$('step').value=state.t;updateTime();$('empty').hidden=!!snap;$('days').replaceChildren();for(let d=0;d<s.daySteps.length;d++){const b=document.createElement('button');b.textContent=(d+1)+'日目';b.disabled=!days().some(e=>e.day===d);b.className=d===state.day?'active':'';b.onclick=()=>{state.day=d;state.t=0;state.playing=false;state.follow=false;build();renderUI();draw();};$('days').append(b);}
$('cars').replaceChildren();if(snap)for(let id=0;id<snap.agents.length;id++){const a=snap.agents[id],at=carAt(id),color=colors[id%colors.length],el=document.createElement('div');el.className='car'+(state.selected===id?' selected':'');el.style.setProperty('--car-color',color);el.tabIndex=0;el.setAttribute('role','button');el.onclick=()=>{state.selected=state.selected===id?null:id;renderUI();draw();};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click();}};const isSupply=a.kind===1;el.innerHTML=`<div class="car-top"><div class="car-name"><span class="car-dot">${isSupply?'■':'●'}</span>${isSupply?'補給車':'巡回車'} ${id}</div><small>ID ${id}</small></div><div class="car-info"><div><small>日開始位置</small><strong>${a.pos}</strong></div><div><small>計画位置</small><strong>${at?.pos??'—'}</strong></div><div><small>開始燃料</small><strong>${a.fuel}</strong></div></div><div class="fuel-bar"><i style="width:${Math.max(0,Math.min(100,a.fuel/s.fuelLimits*100))}%"></i></div>`;$('cars').append(el);}
$('events').replaceChildren();function event(text,small){const el=document.createElement('div');el.className='event';el.textContent=text;if(small){const sub=document.createElement('small');sub.textContent=small;el.append(sub);}$('events').append(el);}
if(rev>0){badge($('revision'),'採用 · rev '+rev,'good');event('全車の回答が採用されました','HTTP '+p.http+' / revision '+rev);}else if(rev===-1){badge($('revision'),'リジェクト','bad');event('回答全体がリジェクトされました','表示中の経路は実行されていない計画です。');}else{badge($('revision'),'回答待ち');event(snap?'経路を計算しています':'日次データの取得を待っています');}
for(const e of r.events.filter(e=>e.type==='sync'&&e.day===state.day)){for(const a of e.supplies||[]){if(state.selected!==null&&state.selected!==a.supply_id&&state.selected!==a.tourcar_id)continue;const pos=cellId(a.meeting_point,s.map.width);event('補給車 '+a.supply_id+' → 巡回車 '+a.tourcar_id,'合流セル '+pos+' / '+a.refuel_at+' step で待機終了');}}
const next=days().find(d=>d.day===state.day+1);if(next&&snap){event('翌日の実状態',next.agents.map((a,i)=>'ID '+i+': '+a.pos+' / 燃料 '+a.fuel).join(' · '));}if(!r.events.some(e=>e.type==='sync'))event('この記録に合流の詳細はありません','新しい試合では途中待機と合流時刻も記録されます。');$('payload').textContent=p?JSON.stringify(p.payload,null,2):'まだ回答はありません';$('play').disabled=!p;}
function updateTime(){$('step-label').textContent=Math.floor(state.t)+' / '+(state.data?.source.daySteps[state.day]||0)+' step';$('step').value=state.t;$('play').textContent=state.playing?'Ⅱ':'▶';}
function draw(){if(!state.data)return;const bounds=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=Math.round(bounds.width*dpr);canvas.height=Math.round(bounds.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,bounds.width,bounds.height);const s=state.data.source,w=s.map.width,h=s.map.height,base=Math.min((bounds.width-60)/(Math.sqrt(3)*12*w+12),(bounds.height-60)/(18*h+6));const scale=base*state.zoom;view={scale,x:(bounds.width-Math.sqrt(3)*12*(w-1)*scale)/2+state.pan.x,y:(bounds.height-18*(h-1)*scale)/2+state.pan.y};const radius=12*scale;for(let row=0;row<h;row++)for(let col=0;col<w;col++){const id=row*w+col,p=point(id);if(p.x<-radius||p.x>bounds.width+radius||p.y<-radius||p.y>bounds.height+radius)continue;ctx.beginPath();for(let j=0;j<6;j++){const angle=(60*j-30)*Math.PI/180;ctx.lineTo(p.x+radius*Math.cos(angle),p.y+radius*Math.sin(angle));}ctx.closePath();ctx.fillStyle=terrainColors[s.map.cells[row][col]];ctx.globalAlpha=.78;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle='#0c1c26';ctx.lineWidth=.7;ctx.stroke();if($('numbers').checked&&radius>7){ctx.fillStyle='#13222b';ctx.font=Math.max(6,radius*.52)+'px system-ui';ctx.textAlign='center';ctx.fillText(id,p.x,p.y+3);}}
for(const spot of s.spots){const p=point(spot.pos);ctx.beginPath();ctx.arc(p.x,p.y,radius*.47,0,Math.PI*2);ctx.fillStyle=['#ffe69a','#deabf3','#94eaf1','#ffb7a4'][spot.brand%4];ctx.fill();ctx.strokeStyle='#13222b';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#13222b';ctx.font='bold '+Math.max(7,radius*.6)+'px system-ui';ctx.textAlign='center';ctx.fillText('S',p.x,p.y+radius*.19);}
if($('paths').checked)for(const line of state.timelines){if(state.selected!==null&&state.selected!==line.id)ctx.globalAlpha=.15;else ctx.globalAlpha=.9;ctx.strokeStyle=colors[line.id%colors.length];ctx.lineWidth=state.selected===line.id?3:2;ctx.setLineDash(revision()===-1?[6,4]:[]);ctx.beginPath();line.route.forEach((id,i)=>{const p=point(id);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);});ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;}
const snap=snapshot();if(snap)snap.agents.forEach((a,id)=>{const at=carAt(id),p=point(at.pos),color=colors[id%colors.length],offset=(id%3-1)*radius*.24;ctx.globalAlpha=(state.selected!==null&&state.selected!==id) ? .4 : 1;ctx.fillStyle=color;ctx.strokeStyle='#0d1a23';ctx.lineWidth=2;const r=Math.max(5,radius*.39);ctx.beginPath();if(a.kind===1)ctx.rect(p.x-r+offset,p.y-r+offset,r*2,r*2);else ctx.arc(p.x+offset,p.y+offset,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#08212a';ctx.textAlign='center';ctx.font='bold '+Math.max(8,r*.95)+'px system-ui';ctx.fillText(id,p.x+offset,p.y+offset+3);if(at.wait){ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(p.x+offset,p.y+offset,r+4,0,Math.PI*2);ctx.stroke();}ctx.globalAlpha=1;});}
async function load(reset=false){if(!state.map)return;const ticket=++state.request;try{const data=await api('/api/run/'+encodeURIComponent(state.map));if(ticket!==state.request)return;state.data=data;if(reset){state.day=0;state.t=0;state.selected=null;state.zoom=1;state.pan={x:0,y:0};}if(state.follow&&data.result.running&&days().length)state.day=days().at(-1).day;build();renderUI();draw();const listing=await api('/api/maps');$('run').disabled=!listing.can_run||listing.running.length>0;}catch(e){$('notice').textContent=e.message;}}
$('map').onchange=()=>{state.map=$('map').value;state.follow=false;state.playing=false;load(true);};$('run').onclick=async()=>{try{state.playing=false;await api('/api/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({map:state.map,fast:$('fast').checked})});state.follow=true;await load(true);}catch(e){$('notice').textContent=e.message;}};$('step').oninput=()=>{state.t=Number($('step').value);state.playing=false;updateTime();renderUI();draw();};$('play').onclick=()=>{if(state.t>=Number($('step').max))state.t=0;state.playing=!state.playing;state.last=performance.now();updateTime();};$('paths').onchange=draw;$('numbers').onchange=draw;$('all-cars').onclick=()=>{state.selected=null;renderUI();draw();};$('reset').onclick=()=>{state.zoom=1;state.pan={x:0,y:0};draw();};canvas.onwheel=e=>{e.preventDefault();state.zoom=Math.max(.6,Math.min(7,state.zoom*(e.deltaY>0?.9:1.1)));draw();};canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);$('tooltip').hidden=true;};canvas.onpointerup=()=>drag=null;canvas.onpointermove=e=>{if(drag){state.pan.x+=e.clientX-drag.x;state.pan.y+=e.clientY-drag.y;drag={x:e.clientX,y:e.clientY};draw();return;}if(!state.data)return;const b=canvas.getBoundingClientRect(),x=e.clientX-b.left,y=e.clientY-b.top,w=state.data.source.map.width,h=state.data.source.map.height;const row=Math.round((y-view.y)/(18*view.scale)),col=Math.round((x-view.x)/(Math.sqrt(3)*12*view.scale)+(row%2)/2);if(row<0||row>=h||col<0||col>=w){$('tooltip').hidden=true;return;}const id=row*w+col,code=state.data.source.map.cells[row][col],spot=state.data.source.spots.find(s=>s.pos===id);$('tooltip').hidden=false;$('tooltip').textContent='セル '+id+' ('+col+', '+row+')\n'+terrain[code]+' / 移動コスト '+duration(id,snapshot())+' step'+(spot?'\nスポット 系列 '+spot.brand+' / 最大在庫 '+spot.stocks:'');$('tooltip').style.left=Math.min(x+15,b.width-185)+'px';$('tooltip').style.top=Math.max(8,y-70)+'px';};canvas.onpointerleave=()=>{$('tooltip').hidden=true;};window.onresize=draw;
function animate(now){if(state.playing){state.t+=Math.min(.2,(now-state.last)/1000)*Number($('speed').value);const max=Number($('step').max);if(state.t>=max){state.t=max;state.playing=false;}updateTime();draw();}state.last=now;requestAnimationFrame(animate);}requestAnimationFrame(animate);
(async()=>{try{const listing=await api('/api/maps');for(const map of listing.maps){const opt=document.createElement('option');opt.value=map.id;opt.textContent=map.id+' · '+map.width+'×'+map.height;$('map').append(opt);}if(!listing.maps.length){$('notice').textContent='マップがありません。--maps にJSONファイルを指定してください。';$('run').disabled=true;return;}state.map=listing.maps[0].id;await load(true);setInterval(()=>load(),1200);}catch(e){$('notice').textContent=e.message;badge($('connection'),'接続エラー','bad');}})();
